package info.jtrac.exporter.i18n;

import java.util.HashMap;
import java.util.Map;

public class I18nMessages {

    private final String lang;
    private static final Map<String, Map<String, String>> DICTS = new HashMap<>();

    static {
        // Traditional Chinese (zh-TW)
        Map<String, String> tw = new HashMap<>();
        tw.put("app.title", "JTrac 議題討論串靜態匯出");
        tw.put("nav.spaces", "專案空間總覽");
        tw.put("nav.back_to_index", "← 返回專案總覽");
        tw.put("table.prefix", "空間代碼");
        tw.put("table.name", "空間名稱");
        tw.put("table.description", "說明");
        tw.put("table.total_items", "議題數");
        tw.put("table.actions", "操作");
        tw.put("action.view_threads", "檢視討論串");
        tw.put("issue.id", "議題編號");
        tw.put("issue.summary", "主題");
        tw.put("issue.detail", "詳細說明");
        tw.put("issue.status", "狀態");
        tw.put("issue.severity", "嚴重度");
        tw.put("issue.priority", "優先級");
        tw.put("issue.logged_by", "提出者");
        tw.put("issue.assigned_to", "指派對象");
        tw.put("issue.timestamp", "建立時間");
        tw.put("issue.planned_effort", "預估工時");
        tw.put("issue.no_items", "此專案空間目前尚無任何議題紀錄。");
        tw.put("thread.title", "討論串歷程與留言記錄");
        tw.put("thread.updates", "則更新歷程");
        tw.put("thread.comment", "留言回覆");
        tw.put("thread.status_changed_to", "狀態更迭為");
        tw.put("thread.no_comments", "此議題尚無後續回覆或更迭記錄。");
        tw.put("attachment.title", "附加檔案");
        tw.put("attachment.download", "點擊下載");
        tw.put("attachment.missing", "實體檔案未提供或不存在");
        tw.put("status.open", "開啟 (Open)");
        tw.put("status.closed", "結案 (Closed)");
        tw.put("status.new", "新建 (New)");
        tw.put("footer.exported_at", "報表匯出時間");
        tw.put("footer.powered_by", "本靜態報表由 JTrac Standalone Exporter 自動產出");
        DICTS.put("zh-tw", tw);
        DICTS.put("zh", tw);

        // English (en)
        Map<String, String> en = new HashMap<>();
        en.put("app.title", "JTrac Issue Threads Static Export");
        en.put("nav.spaces", "Spaces Overview");
        en.put("nav.back_to_index", "← Back to Spaces Overview");
        en.put("table.prefix", "Prefix");
        en.put("table.name", "Space Name");
        en.put("table.description", "Description");
        en.put("table.total_items", "Total Issues");
        en.put("table.actions", "Action");
        en.put("action.view_threads", "View Discussion Threads");
        en.put("issue.id", "Issue Key");
        en.put("issue.summary", "Summary");
        en.put("issue.detail", "Description");
        en.put("issue.status", "Status");
        en.put("issue.severity", "Severity");
        en.put("issue.priority", "Priority");
        en.put("issue.logged_by", "Logged By");
        en.put("issue.assigned_to", "Assigned To");
        en.put("issue.timestamp", "Created At");
        en.put("issue.planned_effort", "Planned Effort");
        en.put("issue.no_items", "No issues recorded in this space yet.");
        en.put("thread.title", "Discussion Thread & History");
        en.put("thread.updates", "update(s)");
        en.put("thread.comment", "Comment");
        en.put("thread.status_changed_to", "Status changed to");
        en.put("thread.no_comments", "No follow-up updates yet.");
        en.put("attachment.title", "Attachments");
        en.put("attachment.download", "Download File");
        en.put("attachment.missing", "File not provided or missing locally");
        en.put("status.open", "Open");
        en.put("status.closed", "Closed");
        en.put("status.new", "New");
        en.put("footer.exported_at", "Exported at");
        en.put("footer.powered_by", "Generated by JTrac Standalone Exporter");
        DICTS.put("en", en);

        // Simplified Chinese (zh-CN)
        Map<String, String> cn = new HashMap<>();
        cn.put("app.title", "JTrac 问题讨论串静态导出");
        cn.put("nav.spaces", "空间总览");
        cn.put("nav.back_to_index", "← 返回空间总览");
        cn.put("table.prefix", "空间前缀");
        cn.put("table.name", "空间名称");
        cn.put("table.description", "描述");
        cn.put("table.total_items", "问题数");
        cn.put("table.actions", "操作");
        cn.put("action.view_threads", "查看讨论串");
        cn.put("issue.id", "问题编号");
        cn.put("issue.summary", "主题");
        cn.put("issue.detail", "详细描述");
        cn.put("issue.status", "状态");
        cn.put("issue.severity", "严重度");
        cn.put("issue.priority", "优先级");
        cn.put("issue.logged_by", "报告人");
        cn.put("issue.assigned_to", "经办人");
        cn.put("issue.timestamp", "创建时间");
        cn.put("issue.planned_effort", "预估工时");
        cn.put("issue.no_items", "此空间暂无任何问题记录。");
        cn.put("thread.title", "讨论串记录与跟踪更新");
        cn.put("thread.updates", "条更新记录");
        cn.put("thread.comment", "回复");
        cn.put("thread.status_changed_to", "状态变更为");
        cn.put("thread.no_comments", "此问题暂无后续跟踪或更新记录。");
        cn.put("attachment.title", "附加文件");
        cn.put("attachment.download", "下载文件");
        cn.put("attachment.missing", "本地未提供该文件或文件缺失");
        cn.put("status.open", "开启 (Open)");
        cn.put("status.closed", "已关闭 (Closed)");
        cn.put("status.new", "新建 (New)");
        cn.put("footer.exported_at", "导出时间");
        cn.put("footer.powered_by", "本静态报表由 JTrac 独立导出工具自动生成");
        DICTS.put("zh-cn", cn);

        // Japanese (ja)
        Map<String, String> ja = new HashMap<>();
        ja.put("app.title", "JTrac 課題ディスカッション静的エクスポート");
        ja.put("nav.spaces", "プロジェクト一覧");
        ja.put("nav.back_to_index", "← プロジェクト一覧へ戻る");
        ja.put("table.prefix", "プレフィックス");
        ja.put("table.name", "プロジェクト名");
        ja.put("table.description", "説明");
        ja.put("table.total_items", "課題数");
        ja.put("table.actions", "操作");
        ja.put("action.view_threads", "ディスカッションを表示");
        ja.put("issue.id", "課題キー");
        ja.put("issue.summary", "件名");
        ja.put("issue.detail", "詳細");
        ja.put("issue.status", "ステータス");
        ja.put("issue.severity", "重要度");
        ja.put("issue.priority", "優先度");
        ja.put("issue.logged_by", "報告者");
        ja.put("issue.assigned_to", "担当者");
        ja.put("issue.timestamp", "作成日時");
        ja.put("issue.planned_effort", "見積工数");
        ja.put("issue.no_items", "このプロジェクトには課題が登録されていません。");
        ja.put("thread.title", "ディスカッション履歴・更新記録");
        ja.put("thread.updates", "件の更新履歴");
        ja.put("thread.comment", "コメント");
        ja.put("thread.status_changed_to", "ステータス変更: ");
        ja.put("thread.no_comments", "後続の更新履歴はありません。");
        ja.put("attachment.title", "添付ファイル");
        ja.put("attachment.download", "ダウンロード");
        ja.put("attachment.missing", "ファイルが指定されていないか、存在しません");
        ja.put("status.open", "オープン");
        ja.put("status.closed", "完了");
        ja.put("status.new", "新規");
        ja.put("footer.exported_at", "エクスポート日時");
        ja.put("footer.powered_by", "JTrac スタンドアロンエクスポーターにより生成");
        DICTS.put("ja", ja);

        // Vietnamese (vi)
        Map<String, String> vi = new HashMap<>();
        vi.put("app.title", "Xuất tĩnh luồng thảo luận JTrac");
        vi.put("nav.spaces", "Tổng quan không gian");
        vi.put("nav.back_to_index", "← Quay lại danh sách không gian");
        vi.put("table.prefix", "Tiền tố");
        vi.put("table.name", "Tên không gian");
        vi.put("table.description", "Mô tả");
        vi.put("table.total_items", "Tổng số vấn đề");
        vi.put("table.actions", "Thao tác");
        vi.put("action.view_threads", "Xem thảo luận");
        vi.put("issue.id", "Mã vấn đề");
        vi.put("issue.summary", "Tiêu đề");
        vi.put("issue.detail", "Chi tiết");
        vi.put("issue.status", "Trạng thái");
        vi.put("issue.severity", "Mức độ nghiêm trọng");
        vi.put("issue.priority", "Mức độ ưu tiên");
        vi.put("issue.logged_by", "Người tạo");
        vi.put("issue.assigned_to", "Người thực hiện");
        vi.put("issue.timestamp", "Thời gian tạo");
        vi.put("issue.planned_effort", "Công sức dự kiến");
        vi.put("issue.no_items", "Chưa có vấn đề nào trong không gian này.");
        vi.put("thread.title", "Luồng thảo luận & Lịch sử cập nhật");
        vi.put("thread.updates", "lượt cập nhật");
        vi.put("thread.comment", "Bình luận");
        vi.put("thread.status_changed_to", "Trạng thái chuyển sang");
        vi.put("thread.no_comments", "Chưa có bình luận hoặc cập nhật tiếp theo.");
        vi.put("attachment.title", "Tệp đính kèm");
        vi.put("attachment.download", "Tải xuống");
        vi.put("attachment.missing", "Tệp không được cung cấp hoặc bị thiếu");
        vi.put("status.open", "Đang mở");
        vi.put("status.closed", "Đã đóng");
        vi.put("status.new", "Mới");
        vi.put("footer.exported_at", "Thời gian xuất");
        vi.put("footer.powered_by", "Được tạo tự động bởi JTrac Standalone Exporter");
        DICTS.put("vi", vi);
    }

    public I18nMessages(String lang) {
        if (lang != null) {
            String lower = lang.toLowerCase().replace('_', '-');
            if (DICTS.containsKey(lower)) {
                this.lang = lower;
            } else if (lower.startsWith("zh")) {
                this.lang = lower.contains("cn") ? "zh-cn" : "zh-tw";
            } else if (lower.startsWith("ja")) {
                this.lang = "ja";
            } else if (lower.startsWith("vi")) {
                this.lang = "vi";
            } else if (lower.startsWith("en")) {
                this.lang = "en";
            } else {
                this.lang = "zh-tw";
            }
        } else {
            this.lang = "zh-tw";
        }
    }

    public String get(String key) {
        Map<String, String> dict = DICTS.get(this.lang);
        if (dict != null && dict.containsKey(key)) {
            return dict.get(key);
        }
        // fallback to English
        Map<String, String> en = DICTS.get("en");
        if (en != null && en.containsKey(key)) {
            return en.get(key);
        }
        return key;
    }

    public String getStatusLabel(Integer status) {
        if (status == null) return get("status.open");
        switch (status) {
            case 0:
                return get("status.new");
            case 1:
                return get("status.open");
            case 99:
                return get("status.closed");
            default:
                return get("issue.status") + " #" + status;
        }
    }
}
