package info.jtrac.exporter.i18n;

import java.util.HashMap;
import java.util.Map;

public class I18nMessages {

    private final String lang;
    private static final Map<String, Map<String, String>> DICTS = new HashMap<>();

    static {
        // Traditional Chinese (zh-TW)
        Map<String, String> tw = new HashMap<>();
        tw.put("app.title", "JTrac 議題討論串靜態匯出");
        tw.put("nav.spaces", "專案空間總覽");
        tw.put("nav.back_to_index", "← 返回專案總覽");
        tw.put("table.prefix", "空間代碼");
        tw.put("table.name", "空間名稱");
        tw.put("table.description", "說明");
        tw.put("table.total_items", "議題數");
        tw.put("table.actions", "操作");
        tw.put("action.view_threads", "檢視討論串");
        tw.put("issue.id", "議題編號");
        tw.put("issue.summary", "主題");
        tw.put("issue.detail", "詳細說明");
        tw.put("issue.status", "狀態");
        tw.put("issue.severity", "嚴重度");
        tw.put("issue.priority", "優先級");
        tw.put("issue.logged_by", "提出者");
        tw.put("issue.assigned_to", "指派對象");
        tw.put("issue.timestamp", "建立時間");
        tw.put("issue.planned_effort", "預估工時");
        tw.put("issue.no_items", "此專案空間目前尚無任何議題紀錄。");
        tw.put("thread.title", "討論串歷程與留言記錄");
        tw.put("thread.updates", "則更新歷程");
        tw.put("thread.comment", "留言回覆");
        tw.put("thread.status_changed_to", "狀態更迭為");
        tw.put("thread.no_comments", "此議題尚無後續回覆或更迭記錄。");
        tw.put("attachment.title", "附加檔案");
        tw.put("attachment.download", "點擊下載");
        tw.put("attachment.missing", "實體檔案未提供或不存在");
        tw.put("status.open", "開啟 (Open)");
        tw.put("status.closed", "結案 (Closed)");
        tw.put("status.new", "新建 (New)");
        tw.put("footer.exported_at", "報表匯出時間");
        tw.put("footer.powered_by", "本靜態報表由 JTrac Standalone Exporter 自動產出");
        tw.put("action.toggle_theme", "切換明暗主題");
        // CLI Messages
        tw.put("cli.banner.title", "  JTrac 獨立命令列靜態討論串匯出工具 (CLI)");
        tw.put("cli.lang_mode", "  語言模式: ");
        tw.put("cli.export_target", "  匯出目標: ");
        tw.put("cli.attachments_dir", "  附件目錄: ");
        tw.put("cli.attachments_unspecified", "未指定 (若有附件將標記提示，不中斷匯出)");
        tw.put("cli.connecting_db", "正在連線至資料庫: %s (帳號: %s)");
        tw.put("cli.connected_db", "資料庫連線成功！");
        tw.put("cli.loaded_users", "讀取到 %d 位使用者資料。");
        tw.put("cli.loaded_attachments", "讀取到 %d 筆附件資料。");
        tw.put("cli.loaded_spaces", "讀取到 %d 個專案空間。");
        tw.put("cli.space_filtered", "套用空間篩選，符合之空間數: %d");
        tw.put("cli.loaded_issues", "讀取到 %d 個議題。");
        tw.put("cli.loaded_history", "讀取到 %d 筆討論串歷史更新記錄。");
        tw.put("cli.html_done", "HTML 靜態報表產出完成！輸出目錄: %s");
        tw.put("cli.success", "[OK] 匯出作業順利完成！耗時: %d 毫秒");
        tw.put("cli.open_browser", "[INFO] 請使用瀏覽器開啟: %s");
        tw.put("cli.error_prefix", "[錯誤] 匯出過程發生錯誤: %s");
        DICTS.put("zh-tw", tw);
        DICTS.put("zh", tw);

        // English (en)
        Map<String, String> en = new HashMap<>();
        en.put("app.title", "JTrac Issue Threads Static Export");
        en.put("nav.spaces", "Spaces Overview");
        en.put("nav.back_to_index", "← Back to Spaces Overview");
        en.put("table.prefix", "Prefix");
        en.put("table.name", "Space Name");
        en.put("table.description", "Description");
        en.put("table.total_items", "Total Issues");
        en.put("table.actions", "Action");
        en.put("action.view_threads", "View Discussion Threads");
        en.put("issue.id", "Issue Key");
        en.put("issue.summary", "Summary");
        en.put("issue.detail", "Description");
        en.put("issue.status", "Status");
        en.put("issue.severity", "Severity");
        en.put("issue.priority", "Priority");
        en.put("issue.logged_by", "Logged By");
        en.put("issue.assigned_to", "Assigned To");
        en.put("issue.timestamp", "Created At");
        en.put("issue.planned_effort", "Planned Effort");
        en.put("issue.no_items", "No issues recorded in this space yet.");
        en.put("thread.title", "Discussion Thread & History");
        en.put("thread.updates", "update(s)");
        en.put("thread.comment", "Comment");
        en.put("thread.status_changed_to", "Status changed to");
        en.put("thread.no_comments", "No follow-up updates yet.");
        en.put("attachment.title", "Attachments");
        en.put("attachment.download", "Download File");
        en.put("attachment.missing", "File not provided or missing locally");
        en.put("status.open", "Open");
        en.put("status.closed", "Closed");
        en.put("status.new", "New");
        en.put("footer.exported_at", "Exported at");
        en.put("footer.powered_by", "Generated by JTrac Standalone Exporter");
        en.put("action.toggle_theme", "Toggle Theme");
        // CLI Messages
        en.put("cli.banner.title", "  JTrac Standalone HTML Exporter (CLI)");
        en.put("cli.lang_mode", "  Language Mode: ");
        en.put("cli.export_target", "  Export Target: ");
        en.put("cli.attachments_dir", "  Attachments  : ");
        en.put("cli.attachments_unspecified", "Not specified (attachments will be flagged if present)");
        en.put("cli.connecting_db", "Connecting to database: %s (User: %s)");
        en.put("cli.connected_db", "Database connection established!");
        en.put("cli.loaded_users", "Loaded %d user records.");
        en.put("cli.loaded_attachments", "Loaded %d attachment records.");
        en.put("cli.loaded_spaces", "Loaded %d spaces.");
        en.put("cli.space_filtered", "Applied space filter, matching spaces: %d");
        en.put("cli.loaded_issues", "Loaded %d issues.");
        en.put("cli.loaded_history", "Loaded %d discussion thread history updates.");
        en.put("cli.html_done", "HTML static report generated! Output directory: %s");
        en.put("cli.success", "[OK] Export completed successfully! Elapsed: %d ms");
        en.put("cli.open_browser", "[INFO] Please open in your browser: %s");
        en.put("cli.error_prefix", "[ERROR] Export failed: %s");
        DICTS.put("en", en);

        // Simplified Chinese (zh-CN)
        Map<String, String> cn = new HashMap<>();
        cn.put("app.title", "JTrac 问题讨论串静态导出");
        cn.put("nav.spaces", "空间总览");
        cn.put("nav.back_to_index", "← 返回空间总览");
        cn.put("table.prefix", "空间前缀");
        cn.put("table.name", "空间名称");
        cn.put("table.description", "描述");
        cn.put("table.total_items", "问题数");
        cn.put("table.actions", "操作");
        cn.put("action.view_threads", "查看讨论串");
        cn.put("issue.id", "问题编号");
        cn.put("issue.summary", "主题");
        cn.put("issue.detail", "详细描述");
        cn.put("issue.status", "状态");
        cn.put("issue.severity", "严重度");
        cn.put("issue.priority", "优先级");
        cn.put("issue.logged_by", "报告人");
        cn.put("issue.assigned_to", "经办人");
        cn.put("issue.timestamp", "创建时间");
        cn.put("issue.planned_effort", "预估工时");
        cn.put("issue.no_items", "此空间暂无任何问题记录。");
        cn.put("thread.title", "讨论串记录与跟踪更新");
        cn.put("thread.updates", "条更新记录");
        cn.put("thread.comment", "回复");
        cn.put("thread.status_changed_to", "状态变更为");
        cn.put("thread.no_comments", "此问题暂无后续跟踪或更新记录。");
        cn.put("attachment.title", "附加文件");
        cn.put("attachment.download", "下载文件");
        cn.put("attachment.missing", "本地未提供该文件或文件缺失");
        cn.put("status.open", "开启 (Open)");
        cn.put("status.closed", "已关闭 (Closed)");
        cn.put("status.new", "新建 (New)");
        cn.put("footer.exported_at", "导出时间");
        cn.put("footer.powered_by", "本静态报表由 JTrac 独立导出工具自动生成");
        cn.put("action.toggle_theme", "切换明暗主题");
        // CLI Messages
        cn.put("cli.banner.title", "  JTrac 独立命令行静态讨论串导出工具 (CLI)");
        cn.put("cli.lang_mode", "  语言模式: ");
        cn.put("cli.export_target", "  导出目标: ");
        cn.put("cli.attachments_dir", "  附件目录: ");
        cn.put("cli.attachments_unspecified", "未指定 (若有附件将标记提示，不中断导出)");
        cn.put("cli.connecting_db", "正在连接至数据库: %s (账号: %s)");
        cn.put("cli.connected_db", "数据库连接成功！");
        cn.put("cli.loaded_users", "读取到 %d 位用户数据。");
        cn.put("cli.loaded_attachments", "读取到 %d 笔附件数据。");
        cn.put("cli.loaded_spaces", "读取到 %d 个项目空间。");
        cn.put("cli.space_filtered", "应用空间筛选，符合之空间数: %d");
        cn.put("cli.loaded_issues", "读取到 %d 个问题。");
        cn.put("cli.loaded_history", "读取到 %d 条讨论串历史更新记录。");
        cn.put("cli.html_done", "HTML 静态报表生成完成！输出目录: %s");
        cn.put("cli.success", "[OK] 导出作业顺利完成！耗时: %d 毫秒");
        cn.put("cli.open_browser", "[INFO] 请使用浏览器打开: %s");
        cn.put("cli.error_prefix", "[错误] 导出过程发生错误: %s");
        DICTS.put("zh-cn", cn);

        // Japanese (ja)
        Map<String, String> ja = new HashMap<>();
        ja.put("app.title", "JTrac 課題ディスカッション静的エクスポート");
        ja.put("nav.spaces", "プロジェクト一覧");
        ja.put("nav.back_to_index", "← プロジェクト一覧へ戻る");
        ja.put("table.prefix", "プレフィックス");
        ja.put("table.name", "プロジェクト名");
        ja.put("table.description", "説明");
        ja.put("table.total_items", "課題数");
        ja.put("table.actions", "操作");
        ja.put("action.view_threads", "ディスカッションを表示");
        ja.put("issue.id", "課題キー");
        ja.put("issue.summary", "件名");
        ja.put("issue.detail", "詳細");
        ja.put("issue.status", "ステータス");
        ja.put("issue.severity", "重要度");
        ja.put("issue.priority", "優先度");
        ja.put("issue.logged_by", "報告者");
        ja.put("issue.assigned_to", "担当者");
        ja.put("issue.timestamp", "作成日時");
        ja.put("issue.planned_effort", "見積工数");
        ja.put("issue.no_items", "このプロジェクトには課題が登録されていません。");
        ja.put("thread.title", "ディスカッション履歴・更新記録");
        ja.put("thread.updates", "件の更新履歴");
        ja.put("thread.comment", "コメント");
        ja.put("thread.status_changed_to", "ステータス変更: ");
        ja.put("thread.no_comments", "後続の更新履歴はありません。");
        ja.put("attachment.title", "添付ファイル");
        ja.put("attachment.download", "ダウンロード");
        ja.put("attachment.missing", "ファイルが指定されていないか、存在しません");
        ja.put("status.open", "オープン");
        ja.put("status.closed", "完了");
        ja.put("status.new", "新規");
        ja.put("footer.exported_at", "エクスポート日時");
        ja.put("footer.powered_by", "JTrac スタンドアロンエクスポーターにより生成");
        ja.put("action.toggle_theme", "テーマ切替");
        // CLI Messages
        ja.put("cli.banner.title", "  JTrac スタンドアロン HTML エクスポーター (CLI)");
        ja.put("cli.lang_mode", "  言語モード: ");
        ja.put("cli.export_target", "  出力先: ");
        ja.put("cli.attachments_dir", "  添付ファイルディレクトリ: ");
        ja.put("cli.attachments_unspecified", "未指定 (添付ファイルが存在する場合は注記されます)");
        ja.put("cli.connecting_db", "データベースに接続中: %s (ユーザー: %s)");
        ja.put("cli.connected_db", "データベース接続に成功しました！");
        ja.put("cli.loaded_users", "%d 件のユーザーデータを読み込みました。");
        ja.put("cli.loaded_attachments", "%d 件の添付ファイル情報を読み込みました。");
        ja.put("cli.loaded_spaces", "%d 件のプロジェクトスペースを読み込みました。");
        ja.put("cli.space_filtered", "プロジェクトフィルタ適用後: %d 件");
        ja.put("cli.loaded_issues", "%d 件の課題を読み込みました。");
        ja.put("cli.loaded_history", "%d 件のディスカッション更新履歴を読み込みました。");
        ja.put("cli.html_done", "HTML 静的レポート出力完了！出力先: %s");
        ja.put("cli.success", "[OK] エクスポート完了！所要時間: %d ミリ秒");
        ja.put("cli.open_browser", "[INFO] ブラウザで確認してください: %s");
        ja.put("cli.error_prefix", "[エラー] エクスポート失敗: %s");
        DICTS.put("ja", ja);

        // Vietnamese (vi)
        Map<String, String> vi = new HashMap<>();
        vi.put("app.title", "Xuất tĩnh luồng thảo luận JTrac");
        vi.put("nav.spaces", "Tổng quan không gian");
        vi.put("nav.back_to_index", "← Quay lại danh sách không gian");
        vi.put("table.prefix", "Tiền tố");
        vi.put("table.name", "Tên không gian");
        vi.put("table.description", "Mô tả");
        vi.put("table.total_items", "Tổng số vấn đề");
        vi.put("table.actions", "Thao tác");
        vi.put("action.view_threads", "Xem thảo luận");
        vi.put("issue.id", "Mã vấn đề");
        vi.put("issue.summary", "Tiêu đề");
        vi.put("issue.detail", "Chi tiết");
        vi.put("issue.status", "Trạng thái");
        vi.put("issue.severity", "Mức độ nghiêm trọng");
        vi.put("issue.priority", "Mức độ ưu tiên");
        vi.put("issue.logged_by", "Người tạo");
        vi.put("issue.assigned_to", "Người thực hiện");
        vi.put("issue.timestamp", "Thời gian tạo");
        vi.put("issue.planned_effort", "Công sức dự kiến");
        vi.put("issue.no_items", "Chưa có vấn đề nào trong không gian này.");
        vi.put("thread.title", "Luồng thảo luận & Lịch sử cập nhật");
        vi.put("thread.updates", "lượt cập nhật");
        vi.put("thread.comment", "Bình luận");
        vi.put("thread.status_changed_to", "Trạng thái chuyển sang");
        vi.put("thread.no_comments", "Chưa có bình luận hoặc cập nhật tiếp theo.");
        vi.put("attachment.title", "Tệp đính kèm");
        vi.put("attachment.download", "Tải xuống");
        vi.put("attachment.missing", "Tệp không được cung cấp hoặc bị thiếu");
        vi.put("status.open", "Đang mở");
        vi.put("status.closed", "Đã đóng");
        vi.put("status.new", "Mới");
        vi.put("footer.exported_at", "Thời gian xuất");
        vi.put("footer.powered_by", "Được tạo tự động bởi JTrac Standalone Exporter");
        vi.put("action.toggle_theme", "Đổi giao diện");
        // CLI Messages
        vi.put("cli.banner.title", "  Công cụ xuất tĩnh luồng thảo luận JTrac (CLI)");
        vi.put("cli.lang_mode", "  Chế độ ngôn ngữ: ");
        vi.put("cli.export_target", "  Thư mục đích: ");
        vi.put("cli.attachments_dir", "  Thư mục tệp đính kèm: ");
        vi.put("cli.attachments_unspecified", "Chưa chỉ định (tệp đính kèm sẽ được đánh dấu nếu có)");
        vi.put("cli.connecting_db", "Đang kết nối cơ sở dữ liệu: %s (Tài khoản: %s)");
        vi.put("cli.connected_db", "Kết nối cơ sở dữ liệu thành công!");
        vi.put("cli.loaded_users", "Đã tải %d bản ghi người dùng.");
        vi.put("cli.loaded_attachments", "Đã tải %d bản ghi tệp đính kèm.");
        vi.put("cli.loaded_spaces", "Đã tải %d không gian dự án.");
        vi.put("cli.space_filtered", "Áp dụng bộ lọc không gian, số lượng khớp: %d");
        vi.put("cli.loaded_issues", "Đã tải %d vấn đề.");
        vi.put("cli.loaded_history", "Đã tải %d lịch sử cập nhật thảo luận.");
        vi.put("cli.html_done", "Báo cáo tĩnh HTML đã tạo xong! Thư mục: %s");
        vi.put("cli.success", "[OK] Xuất dữ liệu thành công! Thời gian: %d ms");
        vi.put("cli.open_browser", "[INFO] Vui lòng mở trong trình duyệt: %s");
        vi.put("cli.error_prefix", "[LỖI] Xuất dữ liệu thất bại: %s");
        DICTS.put("vi", vi);

        // German (de)
        Map<String, String> de = new HashMap<>();
        de.put("app.title", "JTrac Statischer Export der Vorgänge und Diskussionen");
        de.put("nav.spaces", "Projekträume Übersicht");
        de.put("nav.back_to_index", "← Zurück zur Übersicht");
        de.put("table.prefix", "Präfix");
        de.put("table.name", "Raumname");
        de.put("table.description", "Beschreibung");
        de.put("table.total_items", "Vorgänge");
        de.put("table.actions", "Aktionen");
        de.put("action.view_threads", "Diskussionen anzeigen");
        de.put("issue.id", "Vorgangs-ID");
        de.put("issue.summary", "Zusammenfassung");
        de.put("issue.detail", "Beschreibung");
        de.put("issue.status", "Status");
        de.put("issue.severity", "Schweregrad");
        de.put("issue.priority", "Priorität");
        de.put("issue.logged_by", "Erstellt von");
        de.put("issue.assigned_to", "Zugewiesen an");
        de.put("issue.timestamp", "Erstellt am");
        de.put("issue.planned_effort", "Geschätzter Aufwand");
        de.put("issue.no_items", "In diesem Projektraum sind noch keine Vorgänge erfasst.");
        de.put("thread.title", "Diskussionsverlauf & Änderungshistorie");
        de.put("thread.updates", "Update(s)");
        de.put("thread.comment", "Kommentar");
        de.put("thread.status_changed_to", "Status geändert zu");
        de.put("thread.no_comments", "Bisher keine weiteren Aktualisierungen vorhanden.");
        de.put("attachment.title", "Dateianhänge");
        de.put("attachment.download", "Herunterladen");
        de.put("attachment.missing", "Datei nicht verfügbar oder fehlt lokal");
        de.put("status.open", "Offen");
        de.put("status.closed", "Geschlossen");
        de.put("status.new", "Neu");
        de.put("footer.exported_at", "Exportiert am");
        de.put("footer.powered_by", "Erstellt durch JTrac Standalone Exporter");
        de.put("action.toggle_theme", "Design wechseln");
        // CLI Messages
        de.put("cli.banner.title", "  JTrac Standalone HTML Exporter (CLI)");
        de.put("cli.lang_mode", "  Sprachmodus: ");
        de.put("cli.export_target", "  Ausgabeziel: ");
        de.put("cli.attachments_dir", "  Anhängeverzeichnis: ");
        de.put("cli.attachments_unspecified", "Nicht angegeben (Anhänge werden markiert falls vorhanden)");
        de.put("cli.connecting_db", "Verbindung zur Datenbank: %s (Benutzer: %s)");
        de.put("cli.connected_db", "Datenbankverbindung erfolgreich hergestellt!");
        de.put("cli.loaded_users", "%d Benutzerdatensätze geladen.");
        de.put("cli.loaded_attachments", "%d Anhangsdatensätze geladen.");
        de.put("cli.loaded_spaces", "%d Projekträume geladen.");
        de.put("cli.space_filtered", "Projektraumfilter angewendet, passende Räume: %d");
        de.put("cli.loaded_issues", "%d Vorgänge/Issues geladen.");
        de.put("cli.loaded_history", "%d Diskussionsverlaufs-Updates geladen.");
        de.put("cli.html_done", "Statischer HTML-Bericht erfolgreich generiert! Ausgabeverzeichnis: %s");
        de.put("cli.success", "[OK] Export erfolgreich abgeschlossen! Dauer: %d ms");
        de.put("cli.open_browser", "[INFO] Bitte im Browser öffnen: %s");
        de.put("cli.error_prefix", "[FEHLER] Export fehlgeschlagen: %s");
        DICTS.put("de", de);

        // Spanish (es)
        Map<String, String> es = new HashMap<>();
        es.put("app.title", "JTrac Exportación Estática de Hilos de Discusión");
        es.put("nav.spaces", "Resumen de Espacios");
        es.put("nav.back_to_index", "← Volver al resumen");
        es.put("table.prefix", "Prefijo");
        es.put("table.name", "Nombre de Espacio");
        es.put("table.description", "Descripción");
        es.put("table.total_items", "Incidencias");
        es.put("table.actions", "Acciones");
        es.put("action.view_threads", "Ver discusiones");
        es.put("issue.id", "Clave");
        es.put("issue.summary", "Asunto");
        es.put("issue.detail", "Descripción");
        es.put("issue.status", "Estado");
        es.put("issue.severity", "Severidad");
        es.put("issue.priority", "Prioridad");
        es.put("issue.logged_by", "Informado por");
        es.put("issue.assigned_to", "Asignado a");
        es.put("issue.timestamp", "Fecha de creación");
        es.put("issue.planned_effort", "Esfuerzo estimado");
        es.put("issue.no_items", "No hay incidencias registradas en este espacio.");
        es.put("thread.title", "Historial de Discusión y Comentarios");
        es.put("thread.updates", "actualización(es)");
        es.put("thread.comment", "Comentario");
        es.put("thread.status_changed_to", "Estado cambiado a");
        es.put("thread.no_comments", "Aún no hay actualizaciones adicionales para esta incidencia.");
        es.put("attachment.title", "Archivos Adjuntos");
        es.put("attachment.download", "Descargar");
        es.put("attachment.missing", "Archivo no proporcionado o inexistente");
        es.put("status.open", "Abierto");
        es.put("status.closed", "Cerrado");
        es.put("status.new", "Nuevo");
        es.put("footer.exported_at", "Exportado el");
        es.put("footer.powered_by", "Generado por JTrac Standalone Exporter");
        es.put("action.toggle_theme", "Cambiar tema");
        // CLI Messages
        es.put("cli.banner.title", "  JTrac Exportador HTML Independiente (CLI)");
        es.put("cli.lang_mode", "  Modo de idioma: ");
        es.put("cli.export_target", "  Destino: ");
        es.put("cli.attachments_dir", "  Directorio de adjuntos: ");
        es.put("cli.attachments_unspecified", "No especificado (los archivos adjuntos se marcarán si existen)");
        es.put("cli.connecting_db", "Conectando a la base de datos: %s (Usuario: %s)");
        es.put("cli.connected_db", "¡Conexión a la base de datos establecida!");
        es.put("cli.loaded_users", "Cargados %d registros de usuarios.");
        es.put("cli.loaded_attachments", "Cargados %d registros de archivos adjuntos.");
        es.put("cli.loaded_spaces", "Cargados %d espacios de proyecto.");
        es.put("cli.space_filtered", "Filtro de espacio aplicado, espacios coincidentes: %d");
        es.put("cli.loaded_issues", "Cargadas %d incidencias.");
        es.put("cli.loaded_history", "Cargadas %d actualizaciones de historial.");
        es.put("cli.html_done", "¡Informe HTML estático generado! Directorio de salida: %s");
        es.put("cli.success", "[OK] ¡Exportación completada con éxito! Tiempo: %d ms");
        es.put("cli.open_browser", "[INFO] Por favor abra en su navegador: %s");
        es.put("cli.error_prefix", "[ERROR] La exportación falló: %s");
        DICTS.put("es", es);

        // French (fr)
        Map<String, String> fr = new HashMap<>();
        fr.put("app.title", "JTrac Exportation Statique des Discussions et Anomalies");
        fr.put("nav.spaces", "Aperçu des Espaces");
        fr.put("nav.back_to_index", "← Retour à l'aperçu");
        fr.put("table.prefix", "Préfixe");
        fr.put("table.name", "Nom de l'Espace");
        fr.put("table.description", "Description");
        fr.put("table.total_items", "Anomalies");
        fr.put("table.actions", "Actions");
        fr.put("action.view_threads", "Voir les discussions");
        fr.put("issue.id", "Clé");
        fr.put("issue.summary", "Résumé");
        fr.put("issue.detail", "Description");
        fr.put("issue.status", "Statut");
        fr.put("issue.severity", "Sévérité");
        fr.put("issue.priority", "Priorité");
        fr.put("issue.logged_by", "Signalé par");
        fr.put("issue.assigned_to", "Assigné à");
        fr.put("issue.timestamp", "Date de création");
        fr.put("issue.planned_effort", "Charge estimée");
        fr.put("issue.no_items", "Aucune anomalie enregistrée dans cet espace.");
        fr.put("thread.title", "Historique des Discussions et Suivi");
        fr.put("thread.updates", "mise(s) à jour");
        fr.put("thread.comment", "Commentaire");
        fr.put("thread.status_changed_to", "Statut changé en");
        fr.put("thread.no_comments", "Aucune mise à jour supplémentaire pour cette anomalie.");
        fr.put("attachment.title", "Pièces Jointes");
        fr.put("attachment.download", "Télécharger");
        fr.put("attachment.missing", "Fichier non fourni ou manquant localement");
        fr.put("status.open", "Ouvert");
        fr.put("status.closed", "Fermé");
        fr.put("status.new", "Nouveau");
        fr.put("footer.exported_at", "Exporté le");
        fr.put("footer.powered_by", "Généré par JTrac Standalone Exporter");
        fr.put("action.toggle_theme", "Basculer de thème");
        // CLI Messages
        fr.put("cli.banner.title", "  Exportateur HTML Autonome JTrac (CLI)");
        fr.put("cli.lang_mode", "  Mode de langue: ");
        fr.put("cli.export_target", "  Cible d'exportation: ");
        fr.put("cli.attachments_dir", "  Dossier des pièces jointes: ");
        fr.put("cli.attachments_unspecified", "Non spécifié (les pièces jointes seront signalées si existantes)");
        fr.put("cli.connecting_db", "Connexion à la base de données: %s (Utilisateur: %s)");
        fr.put("cli.connected_db", "Connexion à la base de données établie avec succès !");
        fr.put("cli.loaded_users", "%d enregistrements utilisateurs chargés.");
        fr.put("cli.loaded_attachments", "%d enregistrements de pièces jointes chargés.");
        fr.put("cli.loaded_spaces", "%d espaces de projet chargés.");
        fr.put("cli.space_filtered", "Filtre d'espace appliqué, espaces correspondants: %d");
        fr.put("cli.loaded_issues", "%d tickets/anomalies chargés.");
        fr.put("cli.loaded_history", "%d mises à jour d'historique de discussion chargées.");
        fr.put("cli.html_done", "Rapports HTML statiques générés avec succès ! Répertoire de sortie: %s");
        fr.put("cli.success", "[OK] Exportation terminée avec succès ! Temps écoulé: %d ms");
        fr.put("cli.open_browser", "[INFO] Veuillez ouvrir dans votre navigateur: %s");
        fr.put("cli.error_prefix", "[ERREUR] Échec de l'exportation: %s");
        DICTS.put("fr", fr);
    }

    public I18nMessages(String lang) {
        if (lang != null) {
            String lower = lang.toLowerCase().replace('_', '-');
            if (DICTS.containsKey(lower)) {
                this.lang = lower;
            } else if (lower.startsWith("zh")) {
                this.lang = lower.contains("cn") ? "zh-cn" : "zh-tw";
            } else if (lower.startsWith("ja")) {
                this.lang = "ja";
            } else if (lower.startsWith("vi")) {
                this.lang = "vi";
            } else if (lower.startsWith("de")) {
                this.lang = "de";
            } else if (lower.startsWith("es")) {
                this.lang = "es";
            } else if (lower.startsWith("fr")) {
                this.lang = "fr";
            } else if (lower.startsWith("en")) {
                this.lang = "en";
            } else {
                this.lang = "zh-tw";
            }
        } else {
            this.lang = "zh-tw";
        }
    }

    public String getLang() {
        return this.lang;
    }

    public String get(String key) {
        Map<String, String> dict = DICTS.get(this.lang);
        if (dict != null && dict.containsKey(key)) {
            return dict.get(key);
        }
        // fallback to English
        Map<String, String> en = DICTS.get("en");
        if (en != null && en.containsKey(key)) {
            return en.get(key);
        }
        return key;
    }

    public String getStatusLabel(Integer status) {
        if (status == null) return get("status.open");
        switch (status) {
            case 0:
                return get("status.new");
            case 1:
                return get("status.open");
            case 99:
                return get("status.closed");
            default:
                return get("issue.status") + " #" + status;
        }
    }
}
